export const REQUEST_COLLECTIONS                   = 'REQUEST_COLLECTIONS'
export const RECEIVE_COLLECTIONS                   = 'RECEIVE_COLLECTIONS'
export const COLLECTIONS_FETCH_ERROR               = 'COLLECTIONS_FETCH_ERROR'
export const INVALIDATE_COLLECTIONS                = 'INVALIDATE_COLLECTIONS'

export const REQUEST_COLLECTION                    = 'REQUEST_COLLECTION'
export const RECEIVE_COLLECTION                    = 'RECEIVE_COLLECTION'
export const COLLECTION_FETCH_ERROR                = 'COLLECTION_FETCH_ERROR'
export const INVALIDATE_COLLECTION                 = 'INVALIDATE_COLLECTION'

export const REQUEST_COLLECTION_NEWS_ITEM_ADDITION = 'REQUEST_COLLECTION_NEWS_ITEM_ADDITION'
export const REQUEST_COLLECTION_NEWS_ITEM_REMOVAL  = 'REQUEST_COLLECTION_NEWS_ITEM_REMOVAL'
