version: '2'
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_DB:       flambo
      POSTGRES_USER:     pg
      POSTGRES_PASSWORD: pg

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      http.host:              0.0.0.0
      xpack.security.enabled: 'false'

  api:
    build: ./api
    depends_on:
      - postgres
      - elastic
    environment:
      PORT:            80
      STATIC_BASE_URL: http://localhost:80/static
      POSTGRES_HOST:   postgres
      POSTGRES_PORT:   5432
      POSTGRES_USER:   pg
      POSTGRES_PWD:    pg
      POSTGRES_DB:     flambo
      ELASTIC_HOST:    http://elastic
      ELASTIC_PORT:    9200
