version: '2'
services:
  modules:
    build:
      context: .
      dockerfile: ./docker/modules/Dockerfile
    volumes:
      - /flambo/node_modules

  rethink:
    image: rethinkdb:2.3.4
    ports:
      - "8080:8080"

  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "4000:3000"

  api:
    build: ./docker/api
    depends_on:
      - modules
      - rethink
      - elastic
      - rabbit
    ports:
      - "3000:3000"
    environment:
      NODE_ENV:           ${NODE_ENV}
      APP_PORT:           3000
      ELASTIC_HOST:       elastic
      ELASTIC_PORT:       9200
      RABBITMQ_HOST:      rabbit
      RETHINKDB_HOST:     rethink
      RETHINKDB_PORT:     28015
      RETHINKDB_AUTH_KEY: ""
      RETHINKDB_DB:       flambo
      JWT_SECRET:         s0S3Kr33tZ
    volumes:
      - ./api:/flambo/api
    volumes_from:
      - modules

  worker:
    build: ./docker/worker
    depends_on:
      - modules
      - rethink
      - elastic
      - rabbit
    environment:
      NODE_ENV:           ${NODE_ENV}
      ELASTIC_HOST:       elastic
      ELASTIC_PORT:       9200
      RABBITMQ_HOST:      rabbit
      RETHINKDB_HOST:     rethink
      RETHINKDB_PORT:     28015
      RETHINKDB_AUTH_KEY: ""
      RETHINKDB_DB:       flambo
    volumes:
      - ./api:/flambo/worker
    volumes_from:
      - modules