export const REQUEST_USERS     = 'REQUEST_USERS'
export const RECEIVE_USERS     = 'RECEIVE_USERS'
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR'
export const INVALIDATE_USERS  = 'INVALIDATE_USERS'

export const REQUEST_USER      = 'REQUEST_USER'
export const RECEIVE_USER      = 'RECEIVE_USER'
export const USER_FETCH_ERROR  = 'USER_FETCH_ERROR'
