export const REQUEST_TOPICS               = 'REQUEST_TOPICS'
export const RECEIVE_TOPICS               = 'RECEIVE_TOPICS'
export const TOPICS_FETCH_ERROR           = 'TOPICS_FETCH_ERROR'
export const INVALIDATE_TOPICS            = 'INVALIDATE_TOPICS'

export const REQUEST_TOPIC                = 'REQUEST_TOPIC'
export const RECEIVE_TOPIC                = 'RECEIVE_TOPIC'
export const TOPIC_FETCH_ERROR            = 'TOPIC_FETCH_ERROR'
export const INVALIDATE_TOPIC             = 'INVALIDATE_TOPIC'

export const REQUEST_TOPIC_CREATION       = 'REQUEST_TOPIC_CREATION'
export const TOPIC_CREATION_SUCCESS       = 'TOPIC_CREATION_SUCCESS'
export const TOPIC_CREATION_ERROR         = 'TOPIC_CREATION_ERROR'

export const REQUEST_TOPIC_PICTURE_UPLOAD = 'REQUEST_TOPIC_PICTURE_UPLOAD'
export const TOPIC_PICTURE_UPLOAD_SUCCESS = 'TOPIC_PICTURE_UPLOAD_SUCCESS'

export const REQUEST_TOPIC_UPDATE         = 'REQUEST_TOPIC_UPDATE'
export const TOPIC_UPDATE_SUCCESS         = 'TOPIC_UPDATE_SUCCESS'
export const TOPIC_UPDATE_ERROR           = 'TOPIC_UPDATE_ERROR'

export const REQUEST_TOPIC_NEWS_ITEMS     = 'REQUEST_TOPIC_NEWS_ITEMS'
export const RECEIVE_TOPIC_NEWS_ITEMS     = 'RECEIVE_TOPIC_NEWS_ITEMS'
