export const REQUEST_NEWS_ITEMS                  = 'REQUEST_NEWS_ITEMS'
export const RECEIVE_NEWS_ITEMS                  = 'RECEIVE_NEWS_ITEMS'
export const INVALIDATE_NEWS_ITEMS               = 'INVALIDATE_NEWS_ITEMS'

export const REQUEST_ENTITY_NEWS_ITEMS           = 'REQUEST_ENTITY_NEWS_ITEMS'
export const RECEIVE_ENTITY_NEWS_ITEMS           = 'RECEIVE_ENTITY_NEWS_ITEMS'
export const INVALIDATE_ENTITY_NEWS_ITEMS        = 'INVALIDATE_ENTITY_NEWS_ITEMS'

export const REQUEST_NEWS_ITEMS_STATS            = 'REQUEST_NEWS_ITEMS_STATS'
export const RECEIVE_NEWS_ITEMS_STATS            = 'RECEIVE_NEWS_ITEMS_STATS'
export const INVALIDATE_NEWS_ITEMS_STATS         = 'INVALIDATE_NEWS_ITEMS_STATS'

export const REQUEST_ENTITY_NEWS_ITEMS_STATS     = 'REQUEST_ENTITY_NEWS_ITEMS_STATS'
export const RECEIVE_ENTITY_NEWS_ITEMS_STATS     = 'RECEIVE_ENTITY_NEWS_ITEMS_STATS'
export const INVALIDATE_ENTITY_NEWS_ITEMS_STATS  = 'INVALIDATE_ENTITY_NEWS_ITEMS_STATS'
