export const REQUEST_SOURCES                  = 'REQUEST_SOURCES'
export const RECEIVE_SOURCES                  = 'RECEIVE_SOURCES'
export const SOURCES_FETCH_ERROR              = 'SOURCES_FETCH_ERROR'
export const INVALIDATE_SOURCES               = 'INVALIDATE_SOURCES'

export const REQUEST_SOURCE                   = 'REQUEST_SOURCE'
export const RECEIVE_SOURCE                   = 'RECEIVE_SOURCE'
export const SOURCE_FETCH_ERROR               = 'SOURCE_FETCH_ERROR'
export const INVALIDATE_SOURCE                = 'INVALIDATE_SOURCE'

export const REQUEST_SOURCE_NEWS_ITEMS        = 'REQUEST_SOURCE_NEWS_ITEMS'
export const RECEIVE_SOURCE_NEWS_ITEMS        = 'RECEIVE_SOURCE_NEWS_ITEMS'

export const REQUEST_SOURCE_UPDATE            = 'REQUEST_SOURCE_UPDATE'
export const SOURCE_UPDATE_SUCCESS            = 'SOURCE_UPDATE_SUCCESS'
export const SOURCE_UPDATE_ERROR              = 'SOURCE_UPDATE_ERROR'

export const REQUEST_SOURCE_COLLECTION        = 'REQUEST_SOURCE_COLLECTION'
export const RECEIVE_SOURCE_COLLECTION_STATUS = 'RECEIVE_SOURCE_COLLECTION_STATUS'